customers/urls.py
from django.urls import path

from . import views

app_name = 'customers'
urlpatterns = [
    path('', views.CustomerListView.as_view(), name='list'),
    path('create/', views.CustomerCreate.as_view(), name='create'),
    path('<int:pk>/update/', views.CustomerUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.CustomerDelete.as_view(), name='delete'),
    path('projects/', views.ProjectList.as_view(), name='projects_list'),
    path('projects/create', views.ProjectCreate.as_view(), name='project_create'),
    path('projects/<int:pk>/update/', views.ProjectUpdate.as_view(), name='project_update'),
    path('projects/<int:pk>/delete/', views.ProjectDelete.as_view(), name='project_delete'),
    path('projects/tasks/<int:pk>/update/', views.TaskUpdate.as_view(), name='task_update'),
    path('projects/tasks/<int:pk>/delete/', views.TaskDelete.as_view(), name='task_delete'),
    path('projects/tasks/create/', views.TaskCreate.as_view(), name='task_create'),
    ]

frnote/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('customers/', include('customers.urls', 'customers')),
    path('admin/', admin.site.urls),
]

customers/models.py
from django.db import models


class Customer(models.Model):
    company = models.CharField(max_length=150, unique=True)
    full_name = models.CharField(max_length=150)
    phone = models.CharField(max_length=17)
    email = models.EmailField(blank=True)
    address = models.CharField(max_length=200)
    note = models.CharField(max_length=300, blank=True)

    class Meta:
        ordering = ['company']

    def __str__(self):
        return self.company


class Project(models.Model):
    name = models.CharField(max_length=150)
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)
    description = models.CharField(max_length=300)
    deadline = models.DateField()
    price = models.FloatField()
    paid = models.BooleanField(default=False)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Task(models.Model):
    name = models.CharField(max_length=300)
    project = models.ForeignKey(Project, on_delete=models.PROTECT)
    state_text = models.CharField(max_length=20)
    estimate = models.FloatField()
    deadline = models.DateField()

    def __str__(self):
        return self.name

customers/forms.py
from django import forms
from django.forms import ModelForm, TextInput, EmailInput, Textarea, NumberInput, DateInput, CheckboxInput

from .models import Customer, Project, Task


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['company', 'full_name', 'phone', 'email', 'address', 'note']
        labels = {
            'company': 'Организация',
            'full_name': 'Контактное лицо',
            'phone': 'Телефон',
            'email': 'Email',
            'address': 'Адрес',
            'note': 'Дополнительно',
        }
        widgets = {
            'company': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Организация',
            }),
            'full_name': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Контактное лицо',
            }),
            'phone': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Телефон'
            }),
            'email': EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'Email'
            }),
            'address': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Адрес'
            }),
            'note': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Дополнительно',
                'rows': '2',
            }),
        }


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'customer', 'description', 'deadline', 'price', 'paid', 'completed']
        labels = {
            'name': 'Проект',
            'customer': 'Контрагент',
            'description': 'Описание',
            'deadline': 'Срок сдачи',
            'price': 'Сумма',
            'paid': 'Оплачен',
            'completed': 'Завершен',
        }
        widgets = {
            'name': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Проект',
            }),
            'customer': forms.Select(attrs={
                'class': 'form-control',
                'placeholder': 'Контрагент',
            }),
            'description': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Описание',
                'rows': '2',
            }),
            'deadline': DateInput(attrs={
                'class': 'form-control',
                'placeholder': '2021-12-31',
            }),
            'price': NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'к оплате',
            }),
            'paid': CheckboxInput(attrs={
                'class': 'form-check-input',
            }),
            'completed': CheckboxInput(attrs={
                'class': 'form-check-input',
            }),
        }


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'project', 'state_text', 'estimate', 'deadline']
        labels = {
            'name': 'Задача',
            'project': 'Проект',
            'state_text': 'Статус',
            'estimate': 'Часы',
            'deadline': 'Срок сдачи',
        }
        widgets = {
            'name': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Задача',
            }),
            'project': forms.Select(attrs={
                'class': 'form-control',
                'placeholder': 'Проект',
            }),
            'state_text': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Статус',
            }),
            'estimate': NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Часы',
            }),
            'deadline': DateInput(attrs={
                'class': 'form-control',
                'placeholder': '2021-12-31',
            }),
        }

customers/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, ListView, UpdateView, DeleteView, CreateView

from .forms import CustomerForm, ProjectForm, TaskForm
from .models import Customer, Project, Task


class CustomerCreate(SuccessMessageMixin, CreateView):
    model = Customer
    form_class = CustomerForm
    template_name = 'customers/customer_update.html'
    success_message = 'Контрагент успешно создан'

    def get_success_url(self):
        customer_id = self.object.pk
        return reverse('customers:update', kwargs={'pk': customer_id})

    def get_form_kwargs(self, *args, **kwargs):
            kwargs = super(CustomerCreate, self).get_form_kwargs(*args, **kwargs)
            return kwargs


class CustomerUpdate(SuccessMessageMixin, UpdateView):
    model = Customer
    form_class = CustomerForm
    template_name = 'customers/customer_update.html'
    success_message = 'Контрагент успешно отредактирован'

    def get_success_url(self):
        customer_id = self.kwargs['pk']
        return reverse_lazy('customers:update', kwargs={'pk': customer_id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = context['customer'].project_set.all()
        return context


class CustomerDelete(SuccessMessageMixin, DeleteView):
    model = Customer
    template_name = 'customers/customer_delete.html'
    success_url = reverse_lazy('customers:list')
    success_message = 'Контрагент успешно удален'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = context['customer'].project_set.all()
        return context


class CustomerListView(ListView):
    model = Customer
    template_name = 'customers/customer_list.html'
    context_object_name = 'customers_list'


class ProjectCreate(SuccessMessageMixin, CreateView):
    model = Project
    form_class = ProjectForm
    template_name = 'customers/project_update.html'
    success_message = 'Проект успешно создан'

    def get_success_url(self):
        project_id = self.object.pk
        return reverse('customers:project_update', kwargs={'pk': project_id})

    def get_form_kwargs(self, *args, **kwargs):
            kwargs = super(ProjectCreate, self).get_form_kwargs(*args, **kwargs)
            return kwargs


class ProjectUpdate(SuccessMessageMixin, UpdateView):
    model = Project
    form_class = ProjectForm
    template_name = 'customers/project_update.html'
    success_message = 'Проект успешно отредактирован'

    def get_success_url(self):
        project_id = self.kwargs['pk']
        return reverse_lazy('customers:project_update', kwargs={'pk': project_id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = context['project'].task_set.all()
        return context


class ProjectDelete(SuccessMessageMixin, DeleteView):
    model = Project
    template_name = 'customers/project_delete.html'
    success_url = reverse_lazy('customers:projects_list')
    success_message = 'Проект успешно удален'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = context['project'].task_set.all()
        return context


class ProjectList(ListView):
    model = Project
    context_object_name = 'objects_list'
    template_name = 'customers/projects_list.html'


class TaskUpdate(SuccessMessageMixin, UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'customers/task_update.html'
    success_message = 'Задача успешно отредактирована'

    def get_success_url(self):
        task_id = self.kwargs['pk']
        return reverse_lazy('customers:task_update', kwargs={'pk': task_id})


class TaskCreate(SuccessMessageMixin, CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'customers/task_update.html'
    success_message = 'Задача успешно создана'

    def get_success_url(self):
        task_id = self.object.pk
        return reverse('customers:task_update', kwargs={'pk': task_id})

    def get_form_kwargs(self, *args, **kwargs):
            kwargs = super(TaskCreate, self).get_form_kwargs(*args, **kwargs)
            return kwargs


class TaskDelete(SuccessMessageMixin, DeleteView):
    model = Task

    def get_success_url(self):
        project_id = self.object.project.pk
        return reverse('customers:project_update', kwargs={'pk': project_id})

    def get_form_kwargs(self, *args, **kwargs):
            kwargs = super(TaskDelete, self).get_form_kwargs(*args, **kwargs)
            return kwargs

    def get(self, request, *args, **kwargs):
        messages.success(request, 'Задача успешно удалена')
        return self.post(request, *args, **kwargs)

customers/templates/customers/customer_delete.html
{% extends "base.html" %}
{% load bootstrap_icons %}
{% block title %}Удаление {{ customer }}{% endblock %}
{% block content %}
<div class="col-9">
    {% if object_list %}
    <div class="mt-3">
        <h3>Невозможно удалить
            <a href="{% url 'customers:update' pk=customer.pk %}">{{ customer.company }}</a>
        </h3>
        <h4>у данного контрагента есть проекты:</h4>
    </div>
    <div class="mt-3">
        {% include 'advanced_forms/styled_list.html' with object_url='customers:project_update' %}
    </div>
    {% else %}
    <div class="mt-3">
        <h3>Вы уверены что хотите удалить
            <a href="{% url 'customers:update' pk=customer.pk %}">{{ customer.company }}</a>
            ?
        </h3>
    </div>
    {% endif %}
    <div class="row">
        <div class="col-auto me-auto">
            <div class="mt-4">
                <a href="{% url 'customers:list' %}">
                    <button type="button" class="btn btn-outline-dark">К списку Контрагентов</button>
                </a>
            </div>
        </div>
        {% if not object_list %}
        <div class="col-auto">
            <form action="{{action}}" method="post"> {% csrf_token %}
                <div class="mt-4">
                    <div class="form-group">
                        <input class="btn btn-outline-danger" type="submit" value="Удалить">
                    </div>
                </div>
            </form>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

customers/templates/customers/customer_list.html
{% extends "base.html" %}
{% load bootstrap_icons %}
{% block title %}Контрагенты{% endblock %}
{% block content %}
<div class="row">
    <div class="col-auto me-auto">
        <div class="mt-3">
            <h3>Все контрагенты</h3>
        </div>
    </div>
    <div class="col-auto">
        <div class="mt-3">
            <a href="{% url 'customers:create' %}">
                <button type="button" class="btn btn-outline-dark">
                    {% bs_icon 'plus-square' %}Новый Контрагент
                </button>
            </a>
        </div>
    </div>
</div>
<table class="table align-middle table-striped">
    {% for customer in customers_list %}
    <tr>
        <td>
            <a href="{% url 'customers:update' pk=customer.pk %}">{{ customer.company }}</a>
        </td>
        <td>
            <a href="{% url 'customers:update' pk=customer.pk %}">{{ customer.full_name }}</a>
        </td>
        <td>
            <div class="text-end">
                <a href="{% url 'customers:delete' pk=customer.pk %}">
                    <button type="button" class="btn btn-outline-dark">
                        {% bs_icon 'trash' %}Удалить
                    </button>
                </a>
            </div>
        </td>
    </tr>
    {% empty %}
    <h4>Список контрагентов пуст</h4>
    {% endfor %}
</table>

{% endblock %}

customers/templates/customers/customer_update.html
{% extends 'base.html' %}
{% load bootstrap_icons %}
{% block title %}{{object}}{% endblock %}
{% block content %}
<form class="form-contact" action="" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <fieldset>
            <div>
                <div class="row justify-content-start">
                    <div class="col-7 m-3">
                        <div class="">
                            <h4>Контрагент</h4>
                        </div>
                        <div class="mt-3">
                            {{form.company.label}}
                            {{form.company}}
                        </div>
                        <div class="mt-3">
                            {{form.full_name.label}}
                            {{form.full_name}}
                        </div>
                        <div class="mt-3">
                            <div class="row justify-content-start">
                                <div class="col-7">
                                    {{form.phone.label}}
                                    {{form.phone}}
                                </div>
                                <div class="col-5">
                                    {{form.email.label}}
                                    {{form.email}}
                                </div>
                            </div>
                        </div>
                        <div class="mt-3">
                            {{form.address.label}}
                            {{form.address}}
                        </div>
                        <div class="mt-3">
                            {{form.note.label}}
                            {{form.note}}
                        </div>
                        <div class="row">
                            <div class="col-auto me-auto">
                                <div class="mt-4">
                                    <a href="{% url 'customers:list' %}">
                                        <button type="button" class="btn btn-outline-dark">К списку Контрагентов
                                        </button>
                                    </a>
                                </div>
                            </div>
                            <div class="col-auto">
                                <div class="mt-4">
                                    <div class="form-group">
                                        <input class="btn btn-outline-success" type="submit" value="Сохранить">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% if object %}
                    <div class="col m-3">
                        <div class="row">
                            <div class="col-auto me-auto">
                                <h4>Проекты</h4>
                            </div>
                            <div class="col-auto">
                                <div class="mt-0">
                                    <a href="{% url 'customers:project_create' %}">
                                        <button type="button" class="btn btn-outline-dark">
                                            {% bs_icon 'plus-square' %}Новый Проект
                                        </button>
                                    </a>
                                </div>
                            </div>
                        </div>
                        {% include 'advanced_forms/styled_list.html' with object_url='customers:project_update' %}
                    </div>
                    {% endif %}
                </div>
            </div>
        </fieldset>
    </div>
</form>
{% endblock %}

customers/templates/customers/project_delete.html
{% extends "base.html" %}
{% load bootstrap_icons %}
{% block title %}Удаление {{ object }}{% endblock %}
{% block content %}
<div class="col-9">
    {% if object_list %}
    <div class="mt-3">
        <h3>Невозможно удалить
            <a href="{% url 'customers:project_update' pk=object.pk %}">{{ object.name }}</a>
        </h3>
        <h4>у данного проекта есть задачи:</h4>
    </div>
    <div class="mt-3">
        {% include 'advanced_forms/styled_list.html' with object_url='customers:task_update' %}
    </div>
    {% else %}
    <div class="mt-3">
        <h3>Вы уверены что хотите удалить
            <a href="{% url 'customers:project_update' pk=object.pk %}">{{ object.name }}</a>
            ?
        </h3>
    </div>
    {% endif %}
    <div class="row">
        <div class="col-auto me-auto">
            <div class="mt-4">
                <a href="{% url 'customers:projects_list' %}">
                    <button type="button" class="btn btn-outline-dark">К списку Проектов</button>
                </a>
            </div>
        </div>
        {% if not object_list %}
        <div class="col-auto">
            <form action="{{action}}" method="post"> {% csrf_token %}
                <div class="mt-4">
                    <div class="form-group">
                        <input class="btn btn-outline-danger" type="submit" value="Удалить">
                    </div>
                </div>
            </form>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

customers/templates/customers/project_list.html
{% extends "base.html" %}
{% load bootstrap_icons %}
{% block title %}Проекты{% endblock %}
{% block content %}
<div class="row">
    <div class="col-auto me-auto">
        <div class="mt-3">
            <h3>Все проекты</h3>
        </div>
    </div>
    <div class="col-auto">
        <div class="mt-3">
            <a href="{% url 'customers:project_create' %}">
                <button type="button" class="btn btn-outline-dark">
                    {% bs_icon 'plus-square' %}Новый Проект
                </button>
            </a>
        </div>
    </div>
</div>
<table class="table align-middle table-striped">
    {% for object in objects_list %}
    <tr>
        <td>
            <a href="{% url 'customers:project_update' pk=object.pk %}">{{ object.name }}</a>
        </td>
        <td>
            <a href="{% url 'customers:update' pk=object.customer.pk %}">{{ object.customer.company }}</a>
        </td>
        <td>
            {{ object.deadline }}
        </td>
        <td>
            <div class="text-end">
                <a href="{% url 'customers:project_delete' pk=object.pk %}">
                    <button type="button" class="btn btn-outline-dark">
                        {% bs_icon 'trash' %}Удалить
                    </button>
                </a>
            </div>
        </td>
    </tr>
    {% empty %}
    <h4>Список проектов пуст</h4>
    {% endfor %}
</table>
{% endblock %}

customers/templates/customers/project_update.html
{% extends 'base.html' %}
{% load bootstrap_icons %}
{% block title %}{{object}}{% endblock %}
{% block content %}
<form class="form-contact" action="" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <div class="row">
            <div class="col-auto">
                <div class="mt-1">
                    <a href="{% url 'customers:projects_list' %}">
                        <button type="button" class="btn btn-outline-dark">К списку Проектов</button>
                    </a>
                </div>
            </div>
            <div class="col-auto me-auto">
                {% if object %}
                <div class="mt-1">
                    <a href="{% url 'customers:update' pk=object.customer.pk %}">
                        <button type="button" class="btn btn-outline-dark">К Контрагенту</button>
                    </a>
                </div>
                {% endif %}
            </div>
            <div class="col-auto">
                <div class="mt-1">
                    <div class="form-group">
                        <input class="btn btn-outline-success" type="submit" value="Сохранить Проект">
                    </div>
                </div>
            </div>
        </div>
        <fieldset>
            <div class="row justify-content-start">
                <div class="col">
                    <div class="mt-3">
                        <h4>Проект</h4>
                    </div>
                </div>
                <div class="col">
                    <div class="mt-0">
                        <br>
                        {{form.paid}}
                        {{form.paid.label}}
                    </div>
                </div>
                <div class="col">
                    <div class="mt-0">
                        <br>
                        {{form.completed}}
                        {{form.completed.label}}
                    </div>
                </div>
            </div>
            <div class="row justify-content-start">
                <div class="col-5">
                    <div class="mt-3">
                        {{form.name.label}}
                        {{form.name}}
                    </div>
                </div>
                <div class="col-4">
                    <div class="mt-3">
                        {{form.customer.label}}
                        {{form.customer}}
                    </div>
                </div>
                <div class="col">
                    <div class="mt-3">
                        {{form.deadline.label}}
                        {{form.deadline}}
                    </div>
                </div>
                <div class="col">
                    <div class="mt-3">
                        {{form.price.label}}
                        {{form.price}}
                    </div>
                </div>
            </div>
            <div class="mt-3">
                {{form.description.label}}
                {{form.description}}
            </div>
            <div class="mt-3">
            </div>
        </fieldset>
    </div>
    {% if object %}
    <div class="mt-5">
        <div class="row">
            <div class="col-auto me-auto">
                <h4>Задачи</h4>
            </div>
            <div class="col-auto">
                <div class="mt-0">
                    <a href="{% url 'customers:task_create' %}">
                        <button type="button" class="btn btn-outline-dark">
                            {% bs_icon 'plus-square' %}Новая Задача
                        </button>
                    </a>
                </div>
            </div>
        </div>
        <div class="mt-3">
            <table class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th scope="col">Задача</th>
                    <th scope="col">Статус</th>
                    <th scope="col">Часы</th>
                    <th scope="col">Дедлайн</th>
                    <th scope="col">Удалить</th>
                </tr>
                </thead>
                <tbody>
                {% for task in object_list %}
                <tr>
                    <td>
                        <a href="{% url 'customers:task_update' pk=task.pk %}">
                            {{ task.name }}
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'customers:task_update' pk=task.pk %}">
                            {{ task.state_text }}
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'customers:task_update' pk=task.pk %}">
                            {{ task.estimate }}
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'customers:task_update' pk=task.pk %}">
                            {{ task.deadline }}
                        </a>
                    </td>
                    <td>
                        <div class="text-center">
                            <a href="{% url 'customers:task_delete' pk=task.pk %}">
                                <button type="button" class="btn btn-outline-dark">
                                    {% bs_icon 'trash' %}
                                </button>
                            </a>
                        </div>
                    </td>
                </tr>
                {% empty %}
                {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
        </fieldset>
    </div>
</form>
{% endblock %}

customers/templates/customers/task_update.html
{% extends 'base.html' %}
{% load bootstrap_icons %}
{% block title %}{{object}}{% endblock %}
{% block content %}
<form class="form-contact" action="" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <fieldset>
            <div>
                <div class="row justify-content-start">
                    <div class="col mt-3">
                        <div class="">
                            <h4>Задача</h4>
                        </div>
                        <div class="row justify-content-start">
                            <div class="col">
                                <div class="mt-3">
                                    {{form.name.label}}
                                    {{form.name}}
                                </div>
                            </div>
                            <div class="col">
                                <div class="mt-3">
                                    {{form.project.label}}
                                    {{form.project}}
                                </div>
                            </div>
                        </div>
                        <div class="mt-3">
                            <div class="row justify-content-start">
                                <div class="col">
                                    {{form.state_text.label}}
                                    {{form.state_text}}
                                </div>
                                <div class="col">
                                    {{form.estimate.label}}
                                    {{form.estimate}}
                                </div>
                                <div class="col">
                                    {{form.deadline.label}}
                                    {{form.deadline}}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-auto me-auto">
                                {% if object %}
                                <div class="mt-4">
                                    <a href="{% url 'customers:project_update' pk=object.project.pk %}">
                                        <button type="button" class="btn btn-outline-dark">Назад к Проекту</button>
                                    </a>
                                </div>
                                {% endif %}
                            </div>
                            <div class="col-auto">
                                <div class="mt-4">
                                    <div class="form-group">
                                        <input class="btn btn-outline-success" type="submit" value="Сохранить">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</form>
{% endblock %}