customers/urls.py
from django.urls import path

from . import views

app_name = 'customers'
urlpatterns = [
    path('', views.CustomerListView.as_view(), name='list'),
    path('create/', views.CustomerCreate.as_view(), name='create'),
    path('<int:pk>/update/', views.CustomerUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.CustomerDelete.as_view(), name='delete'),
    path('projects/', views.ProjectList.as_view(), name='projects_list'),
    path('projects/create', views.ProjectCreate.as_view(), name='project_create'),
    path('projects/<int:pk>/update/', views.ProjectUpdate.as_view(), name='project_update'),
    path('projects/<int:pk>/delete/', views.ProjectDelete.as_view(), name='project_delete'),
    path('projects/tasks/<int:pk>/update/', views.TaskUpdate.as_view(), name='task_update'),
    path('projects/tasks/<int:pk>/delete/', views.TaskDelete.as_view(), name='task_delete'),
    path('projects/tasks/create/', views.TaskCreate.as_view(), name='task_create'),
    ]

frnote/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('customers/', include('customers.urls', 'customers')),
    path('admin/', admin.site.urls),
]

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#">FrNote</a>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'customers:list' %}">Контрагенты</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'customers:projects_list' %}">Проекты</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <div class="col-10 mx-auto">
        <div class="row">
            <div class="mt-3">
                {% if messages %}
                {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% else %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="col-10 mx-auto">
        {% block content %}{% endblock %}
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
        crossorigin="anonymous"></script>
</body>
</html>